server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.oksp7.mongodb.net/bootcamp-product?retryWrites=true&w=majority

spring:
  application:
    name: customer-service
  cloud:
    config:
        uri: http://localhost:8888
        username: root
        password: admin
debug: false